from pydantic import BaseModel, Field
from typing import List, Optional

class TranscriptSegment(BaseModel):
    text: str
    start: float
    duration: float

class SectionNotes(BaseModel):
    heading: str
    explanation: str
    key_points: List[str]
    examples: List[str] = Field(default_factory=list)
    timestamp: str
    mermaid_diagram: Optional[str] = None   # Mermaid diagram code generated by LLM

class VideoAnalyzeRequest(BaseModel):
    url: str = Field(..., description="The YouTube video URL")
    chunk_size_mins: Optional[int] = Field(30, description="Chunk size in minutes for long videos")

class ChunkInfo(BaseModel):
    part: int
    start_sec: float
    end_sec: float

class VideoAnalyzeResponse(BaseModel):
    video_id: str
    duration: float
    title: str
    chunks: List[ChunkInfo]
    is_long: bool

class GenerateNotesRequest(BaseModel):
    video_id: str
    include_diagrams: bool = Field(True, description="Generate a Mermaid diagram per section using the LLM")

class GenerateNotesChunkRequest(BaseModel):
    video_id: str
    start_sec: float
    end_sec: float
    include_diagrams: bool = Field(True, description="Generate a Mermaid diagram per section using the LLM")

class SectionSummary(BaseModel):
    heading: str
    key_points: List[str]

class GenerateNotesResponse(BaseModel):
    markdown: str
    sections: List[SectionSummary] = Field(default_factory=list)

class ReduceNotesRequest(BaseModel):
    sections: List[SectionSummary]

class ReduceNotesResponse(BaseModel):
    quick_revision: str
    common_questions: str
    markdown: str

class ExportPDFRequest(BaseModel):
    markdown: str
